name: Deploy Backend (dev)

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: osmity/osmity-web-backend
  TAG: dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set backend build metadata
        run: |
          echo "BACK_BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "BACK_COMMIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push dev backend image
        run: |
          docker build \
            --no-cache \
            --build-arg APP_ENV=dev \
            --build-arg BACK_VERSION=dev \
            --build-arg BACK_BUILD_TIME=${BACK_BUILD_TIME} \
            --build-arg BACK_COMMIT_SHA=${BACK_COMMIT_SHA} \
            -t $IMAGE_NAME:${TAG} .

          docker push $IMAGE_NAME:${TAG}

      - name: Deploy to dev server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Osmity/dev
            docker compose pull backend
            docker compose up -d backend
            docker system prune -f
