name: Deploy Backend (prod)

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: osmity/osmity-web-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy tagged version
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Osmity/prod
          
            echo "APP_VERSION=${GITHUB_REF_NAME}" > .env
            echo "Deploying version:"
            cat .env
          
            docker compose pull
            docker compose up -d
            docker system prune -f
