name: Deploy Backend (prod)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy tagged backend
        uses: appleboy/ssh-action@v1.0.3
        env:
          BACK_VERSION: ${{ github.ref_name }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: BACK_VERSION
          script: |
            cd ~/Osmity/prod
            echo "BACK_VERSION=${BACK_VERSION}" > .env.back
            echo "Deploying backend version: ${BACK_VERSION}"

            set -a
            source .env.back
            source .env.front
            set +a

            docker pull osmity/osmity-backend-migrate:${BACK_VERSION}
            docker run --rm \
              --network container:osmity-postgres-prod \
              osmity/osmity-backend-migrate:${BACK_VERSION} \
              -path /migrations \
              -database "postgres://osmity:osmity_prod_password@localhost:5432/osmity_prod?sslmode=disable" up

            docker compose pull backend
            docker compose up -d backend
            docker system prune -f
